In [1]:
sentences = [
    "This is a very important sentence talkign about machine learning",
    "in my presentation about deep learning I present a lot of information",
    "the black and white stripes on the zebra are distracting to the eye",
]

In [2]:
# Version 1, Ollama
# issue is: there is currently no batching
import ollama
import numpy as np

def get_embedding(text):
    emb = ollama.embeddings(model="nomic-embed-text", prompt=text)
    return np.array(emb.embedding, dtype=np.float64)

for sentence in sentences:
    embedding = get_embedding(sentence)
    print(f"{embedding[:5]}: {sentence}")

[ 0.16999382  1.29142618 -2.75172663 -0.44408426  1.76390481]: This is a very important sentence talkign about machine learning
[ 0.13733795  2.12726545 -2.91621256 -2.00080299  0.86584198]: in my presentation about deep learning I present a lot of information
[ 0.45696813  1.45339489 -3.43149137 -0.74820232  0.98290586]: the black and white stripes on the zebra are distracting to the eye


In [3]:
# Version 2, invoke in python process directly
# much faster
from rolling.embedding import GTEEmbeddingModel
model = GTEEmbeddingModel()

embs = model.encode(sentences)
embs

array([[-0.006874,  0.006702, -0.05545 , ...,  0.02563 , -0.03268 ,
         0.01493 ],
       [ 0.01855 , -0.010925, -0.07465 , ...,  0.01913 , -0.00375 ,
         0.02443 ],
       [-0.05508 ,  0.1301  , -0.02461 , ..., -0.01441 , -0.02164 ,
         0.006794]], dtype=float16)

In [4]:
from rolling.embedding import get_similarity
get_similarity(embs[0], embs[1]), get_similarity(embs[0], embs[2]), get_similarity(embs[1], embs[2])

(np.float16(0.7056), np.float16(0.4849), np.float16(0.4492))